server:
  port: 9001
spring:
  application:
    name: onezero-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://192.168.25.132:3306/tensquare_base
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
    instance-id: onezero-base9001
