server:
  port: 9010
spring:
  application:
    name: onezero-friends
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_friend?characterEncoding=UTF8
    username: root
    password: 12345
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.25.132
jwt:
  config:
    key: jack
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true
