server: 
  port: 9003
spring: 
  application:  
    name: onezero-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true
