server:
  port: 9011
spring:
  application:
    name: onezero-manager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
    instance-id: onezero-manager9011
###配置网关
zuul:
  routes:
    onezerobase:
      path: /base/**
      serviceId: onezero-base

