server: 
  port: 9002
spring: 
  application:  
    name: onezero-recruit #指定服务名 不能用下划线分隔 用-分隔
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
