server: 
  port: 9004
spring: 
  application:  
    name: onezero-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.132:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 12345
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.132
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    instance-id: onezero-article9004
    prefer-ip-address: true

